version: "3.8"

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pwa-fooddonation-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pwa-fooddonation-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    working_dir: /app
    command: sh -c "yarn dev --host 0.0.0.0 --port 5173"

  mysql:
    image: mysql:8
    container_name: pwa-fooddonation-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pwa-fooddonation
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP server
    logging:
      driver: 'none'

volumes:
  db_data:
